### ISSUE TITLE
How do I build this outside of Debian/Ubuntu?

### ISSUE THREAD

**Issue by treymerkley** [SteamGridDB/steam-rom-manager#119]
Hey, so I'm on Arch, and I'm having trouble building this.
Here's my latest error code:
```
Error: Exit code: 1. Command failed: /home/trey/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir -t deb --architecture amd64 --name steam-rom-manager --force --after-install /tmp/temp-dir-4oarm8/0-after-install --after-remove /tmp/temp-dir-4oarm8/1-after-remove --description 
 An app for managing ROMs in Steam --version 2.2.18 --package /tmp/steam-rom-manager-2.2.18/release/steam-rom-manager_2.2.18_amd64.deb --maintainer FrogTheFrog <warliukz@gmail.com> --url https://github.com/FrogTheFrog/steam-rom-manager#readme --vendor FrogTheFrog <warliukz@gmail.com> --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 --license GPL-3.0 /tmp/steam-rom-manager-2.2.18/release/linux-unpacked/=/opt/Steam ROM Manager /tmp/steam-rom-manager-2.2.18/src/assets/icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/steam-rom-manager.png /tmp/steam-rom-manager-2.2.18/src/assets/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/steam-rom-manager.png /tmp/steam-rom-manager-2.2.18/src/assets/icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/steam-rom-manager.png /tmp/steam-rom-manager-2.2.18/src/assets/icons/96x96.png=/usr/share/icons/hicolor/96x96/apps/steam-rom-manager.png /tmp/temp-dir-4oarm8/2-Steam ROM Manager.desktop=/usr/share/applications/steam-rom-manager.desktop

{:timestamp=>"2018-08-24T15:48:48.176932-0500", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2018-08-24T15:48:49.541435-0500", :message=>"Process failed: tar failed (exit code 2). Full command was:[\"tar\", \"-C\", \"/tmp/package-dir-staging-719de7d0e1aad464b118bbc90017b22fef1a200cd48e33ab5327faeab20c\", \"-I'/tmp/steam-rom-manager-2.2.18/node_modules/app-builder-bin-linux/x64/app-builder'\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/tmp/package-deb-build-66839b2c21f5dc1d0514bd3fe25f89825e38d80f60c4f90d7ca8be97850d/data.tar.xz\", \".\"]", :level=>:error}

    at /tmp/steam-rom-manager-2.2.18/node_modules/builder-util/src/util.ts:124:16
    at ChildProcess.exithandler (child_process.js:296:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
From previous event:
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at taskManager.addTask._bluebirdLst.default.map.then (/tmp/steam-rom-manager-2.2.18/node_modules/electron-builder-lib/src/platformPackager.ts:123:37)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/tmp/steam-rom-manager-2.2.18/node_modules/electron-builder-lib/src/platformPackager.ts:123:10)
    at LinuxPackager.pack (/tmp/steam-rom-manager-2.2.18/node_modules/electron-builder-lib/src/platformPackager.ts:117:10)
```
What am I doing wrong and how can I fix this?

**Comment by FrogTheFrog** [comment]
Managed to build it on my fresh Arch distro. Just to be sure, could you just run this in SRM's root dir: `npm install && npm run build:dist && npm run build:linux`.

**Comment by treymerkley** [comment]
I ran it twice, because I got an error for not having 7zip and I saw another issue having this, and it built fine the second time. I used [debtap](https://github.com/helixarch/debtap) to repackage it for Arch and it's running now. It never breaks when you need it to, huh? Thanks!
